import type { Metadata } from "next";
import { Athiti } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Nav";;
import Footer from "@/components/Footer";

const athiti = Athiti({ subsets: ["thai"],weight: ["300", "400", "500", "600", "700"] });

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Homepage | Alectric",
    template: "%s | Alectric",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${athiti.className}`}>
        <Navbar />
        <div className="min-h-screen pb-10">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
